# LIBRERIAS

In [7]:
import pandas as pd
import os

In [8]:
# creacion de carpetas
carpeta_data_python = "data_python"
subcarpetas = ["estudiantes", "administrativos"]

# Verificar si la carpeta "data_python" existe
if not os.path.exists(carpeta_data_python):
    # Si no existe, crearla
    os.mkdir(carpeta_data_python)
    print(f"Se ha creado la carpeta '{carpeta_data_python}'.")

# Crear las subcarpetas "estudiantes" y "administrativos" dentro de "data_python"
for subcarpeta in subcarpetas:
    ruta_subcarpeta = os.path.join(carpeta_data_python, subcarpeta)
    # Verificar si la subcarpeta ya existe
    if not os.path.exists(ruta_subcarpeta):
        # Si no existe, crearla
        os.mkdir(ruta_subcarpeta)
        print(f"Se ha creado la subcarpeta '{subcarpeta}' dentro de '{carpeta_data_python}'.")
    else:
        print(f"La subcarpeta '{subcarpeta}' dentro de '{carpeta_data_python}' ya existe.")

La subcarpeta 'estudiantes' dentro de 'data_python' ya existe.
La subcarpeta 'administrativos' dentro de 'data_python' ya existe.


# CARGA DE DATOS

In [9]:
# Leer el archivo .xlsx en un DataFrame
df_estudiante_2014 = pd.read_excel('data_python/estudiantes/inscritos_2014.xlsx')
df_estudiante_2015 = pd.read_excel('data_python/estudiantes/inscritos_2015.xlsx')
df_estudiante_2016 = pd.read_excel('data_python/estudiantes/inscritos_2016.xlsx')
df_estudiante_2017 = pd.read_excel('data_python/estudiantes/inscritos_2017.xlsx')
df_estudiante_2018 = pd.read_excel('data_python/estudiantes/inscritos_2018.xlsx')
df_estudiante_2019 = pd.read_excel('data_python/estudiantes/inscritos_2019.xlsx')
df_estudiante_2020 = pd.read_excel('data_python/estudiantes/inscritos_2020.xlsx')

In [10]:
df_estudiante_2014.head()

MINISTERIO DE EDUCACION NACIONAL Unnamed: 1 Unnamed: 2  \
0    INSCRITOS EN EDUCACIÓN SUPERIOR - COLOMBIA 2014        NaN        NaN   
1  Fecha de corte de la información: mayo 16 de 2016        NaN        NaN   
2  Fuente: Ministerio de Educación Nacional - Sis...        NaN        NaN   
3  La información suministrada corresponde a lo r...        NaN        NaN   
4                                                NaN        NaN        NaN   

  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Unnamed: 9  ... Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26 Unnamed: 27  \
0        NaN  ...         NaN         NaN         NaN         NaN         NaN   
1        NaN  ...         NaN         NaN         NaN         NaN         NaN   
2        NaN  ...         NaN         NaN         NaN         NaN         NaN   
3        NaN  ...         NaN         NaN         NaN         NaN         NaN   
4        NaN  ...         NaN         NaN         NaN         NaN         NaN   

  Unnamed: 28 Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32  
0         NaN         NaN         NaN         NaN         NaN  
1         NaN         NaN         NaN         NaN         NaN  
2         NaN         NaN         NaN         NaN         NaN  
3         NaN         NaN         NaN         NaN         NaN  
4         NaN         NaN         NaN         NaN         NaN  

[5 rows x 33 columns]

# FORMATO

In [11]:
# Funcion para eliminar las filas que no contienen informacion
def eliminar_filas_iniciales(df, n):
    df = df.iloc[n:].reset_index(drop=True)  # Eliminar las primeras n filas y restablecer los índices
    df.columns = df.iloc[0]  # Establecer la nueva primera fila como encabezado
    df = df[1:].reset_index(drop=True)  # Eliminar la antigua primera fila y restablecer los índices nuevamente
    return df

In [12]:
# Eliminamos las filas sin informacion en cada df
df_estudiantes_2014 = eliminar_filas_iniciales(df_estudiante_2014, 5)
df_estudiantes_2015 = eliminar_filas_iniciales(df_estudiante_2015, 5)
df_estudiantes_2016 = eliminar_filas_iniciales(df_estudiante_2016, 5)
df_estudiantes_2017 = eliminar_filas_iniciales(df_estudiante_2017, 5)
df_estudiantes_2018 = eliminar_filas_iniciales(df_estudiante_2018, 7)
df_estudiantes_2019 = eliminar_filas_iniciales(df_estudiante_2019, 8)
df_estudiantes_2020 = eliminar_filas_iniciales(df_estudiante_2020, 8)

In [13]:
df_estudiantes_2020.head(2)

0 CÓDIGO DE LA INSTITUCIÓN IES_PADRE INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)  \
0                     1101      1101        UNIVERSIDAD NACIONAL DE COLOMBIA   
1                     1101      1101        UNIVERSIDAD NACIONAL DE COLOMBIA   

0 PRINCIPAL O SECCIONAL ID SECTOR IES\tSECTOR IES ID CARACTER CARACTER IES  \
0             Principal         1         OFICIAL           4  Universidad   
1             Principal         1         OFICIAL           4  Universidad   

0 CÓDIGO DEL DEPARTAMENTO (IES) DEPARTAMENTO DE DOMICILIO DE LA IES  ...  \
0                            11                         Bogotá D.C.  ...   
1                            11                         Bogotá D.C.  ...   

0      DESC CINE CODIGO DETALLADO CÓDIGO DEL DEPARTAMENTO (PROGRAMA)  \
0  Producción agrícola y ganadera                                 11   
1  Producción agrícola y ganadera                                 11   

0 DEPARTAMENTO DE OFERTA DEL PROGRAMA CÓDIGO DEL MUNICIPIO (PROGRAMA)  \
0                         Bogotá D.C.                           11001   
1                         Bogotá D.C.                           11001   

0 MUNICIPIO DE OFERTA DEL PROGRAMA ID SEXO    SEXO   AÑO SEMESTRE INSCRITOS  
0                     Bogotá, D.C.       1  Hombre  2020        1        87  
1                     Bogotá, D.C.       1  Hombre  2020        2        49  

[2 rows x 39 columns]

In [14]:
# Ver el contenido de las columnas
pd.set_option('display.max_columns', None)
df_estudiantes_2020.describe()

0       CÓDIGO DE LA INSTITUCIÓN  IES_PADRE  \
count                      52390      52390   
unique                       321        275   
top                         2102       2102   
freq                        9223       9223   

0               INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES) PRINCIPAL O SECCIONAL  \
count                                             52390                 52390   
unique                                              275                     2   
top     UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA UNAD             Principal   
freq                                               9223                 49023   

0       ID SECTOR IES\tSECTOR IES  ID CARACTER CARACTER IES  \
count       52390           52390        52390        52390   
unique          2               2            4            4   
top             2         PRIVADA            4  Universidad   
freq        26682           26682        33714        33714   

0      CÓDIGO DEL DEPARTAMENTO (IES) DEPARTAMENTO DE DOMICILIO DE LA IES  \
count                          52390                               52390   
unique                            28                                  28   
top                               11                         Bogotá D.C.   
freq                           29371                               29371   

0      CÓDIGO DEL MUNICIPIO (IES) MUNICIPIO DE DOMICILIO DE LA IES  \
count                       52390                            52390   
unique                         72                               72   
top                         11001                     Bogotá, D.C.   
freq                        29371                            29371   

0      CÓDIGO SNIES DEL PROGRAMA          PROGRAMA ACADÉMICO  \
count                      52390                       52390   
unique                     10982                        5244   
top      SIN PROGRAMA ESPECIFICO  ADMINISTRACION DE EMPRESAS   
freq                         790                        1119   

0      ID NIVEL ACADÉMICO NIVEL ACADÉMICO ID NIVEL DE FORMACIÓN  \
count               52390           52390                 52390   
unique                  2               2                    10   
top                    01        PREGRADO                    06   
freq                35474           35474                 22514   

0      NIVEL DE FORMACIÓN ID METODOLOGÍA METODOLOGÍA ID ÁREA  \
count               52390          52390       52390   52390   
unique                 10              5           5      10   
top         Universitaria             01  Presencial       6   
freq                22514          34907       34907   15797   

0                                ÁREA DE CONOCIMIENTO ID NÚCLEO  \
count                                           52390     52390   
unique                                             10        57   
top     Economía, administración, contaduría y afines        69   
freq                                            15797     12088   

0      NÚCLEO BÁSICO DEL CONOCIMIENTO (NBC)  ID CINE CAMPO AMPLIO  \
count                                 52390                 52390   
unique                                   57                    12   
top                          Administración                     4   
freq                                  12088                 17259   

0                     DESC CINE CAMPO AMPLIO  ID CINE CAMPO ESPECIFICO  \
count                                  52390                     52390   
unique                                    12                        40   
top     Administración de Empresas y Derecho                        41   
freq                                   17259                     14150   

0                 DESC CINE CAMPO ESPECIFICO  ID CINE CODIGO DETALLADO  \
count                                  52390                     52390   
unique                                    40                       107   
top     Educación comercial y administración             

In [15]:
# Ver el contenido de las columnas
df_estudiantes_2014.describe()

0       Código de \nla Institución  IES PADRE  \
count                        38475      38475   
unique                         318        272   
top                           2102       2102   
freq                          4471       4471   

0               Institución de Educación Superior (IES)  \
count                                             38475   
unique                                              272   
top     UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA UNAD   
freq                                               4471   

0      Principal\n o\nSeccional  Id_Sector Sector IES  Id_Caracter  \
count                     38475      38475      38475        38475   
unique                        2          2          2            4   
top                   PRINCIPAL          2    PRIVADA            4   
freq                      35905      21659      21659        24518   

0      Caracter IES  Código del \ndepartamento\n(IES)  \
count         38475                             38475   
unique            4                                28   
top     UNIVERSIDAD                                11   
freq          24518                             20053   

0      Departamento de \ndomicilio de la IES  Código del \nMunicipio\n(IES)  \
count                                  38475                          38475   
unique                                    28                             73   
top                              BOGOTA D.C.                          11001   
freq                                   20053                          20053   

0      Municipio de\ndomicilio de la IES  Código \nSNIES del\nprograma  \
count                              38475                         38475   
unique                                73                          8436   
top                          BOGOTA D.C.                          3274   
freq                               20053                           231   

0               Programa Académico  Id_Nivel Nivel Académico  \
count                        38475     38475           38475   
unique                        3606         2               2   
top     ADMINISTRACION DE EMPRESAS         1        PREGRADO   
freq                          1277     27758           27758   

0       Id_Nivel_Formacion Nivel de Formación  Id_Metodologia Metodología  \
count                38475              38475           38475       38475   
unique                   6                  6               3           3   
top                      6      UNIVERSITARIA               1  PRESENCIAL   
freq                 16780              16780           28214       28214   

0       Id_Area                         Área de Conocimiento  Id_Nucleo  \
count     38475                                        38475      38475   
unique        8                                            8         62   
top           6  ECONOMIA ADMINISTRACION CONTADURIA Y AFINES         69   
freq      12330                                        12330       8755   

0      Núcleo Básico del Conocimiento (NBC)  \
count                                 38475   
unique                                   56   
top                          ADMINISTRACION   
freq                                   8755   

0       Código del \nDepartamento\n(Programa)  \
count                                   38475   
unique                                     33   
top                                        11   
freq                                     9361   

0      Departamento de oferta del programa  \
count                                38475   
unique                                  33   
top                            BOGOTA D.C.   
freq                                  9361   

0       Código del \nMunicipio\n(Programa) Municipio de oferta del programa  \
count                                38475                            38475   
unique                                 291                              284   
top                  

In [16]:
df_estudiantes_2019.columns

Index(['CÓDIGO DE LA INSTITUCIÓN', 'IES_PADRE',
       'INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)', 'PRINCIPAL O SECCIONAL',
       'ID SECTOR IES', 'SECTOR IES', 'ID CARACTER', 'CARACTER IES',
       'CÓDIGO DEL DEPARTAMENTO (IES)', 'DEPARTAMENTO DE DOMICILIO DE LA IES',
       'CÓDIGO DEL MUNICIPIO', 'MUNICIPIO DE DOMICILIO DE LA IES',
       'CÓDIGO SNIES DEL PROGRAMA', 'PROGRAMA ACADÉMICO', 'ID NIVEL ACADÉMICO',
       'NIVEL ACADÉMICO', 'ID NIVEL DE FORMACIÓN', 'NIVEL DE FORMACIÓN',
       'ID METODOLOGÍA', 'METODOLOGÍA', 'ID ÁREA', 'ÁREA DE CONOCIMIENTO',
       'ID NÚCLEO', 'NÚCLEO BÁSICO DEL CONOCIMIENTO (NBC)',
       'ID CINE CAMPO AMPLIO', 'DESC CINE CAMPO AMPLIO',
       'ID CINE CAMPO ESPECIFICO', 'DESC CINE CAMPO ESPECIFICO',
       'ID CINE CODIGO DETALLADO', 'DESC CINE CODIGO DETALLADO',
       'CÓDIGO DEL DEPARTAMENTO (PROGRAMA)',
       'DEPARTAMENTO DE OFERTA DEL PROGRAMA',
       'CÓDIGO DEL MUNICIPIO (PROGRAMA)', 'MUNICIPIO DE OFERTA DEL PROGRAMA',
       'ID SEXO', 

In [17]:
# Notamos que solo hay datos disponibles para los años 2019 y 2020, los cuales hemos separado por el momento.
columnas_a_eliminar = [
    'ID CINE CAMPO AMPLIO', 'DESC CINE CAMPO AMPLIO',
    'ID CINE CAMPO ESPECIFICO', 'DESC CINE CAMPO ESPECIFICO',
    'ID CINE CODIGO DETALLADO', 'DESC CINE CODIGO DETALLADO'
]

In [18]:
df_estudiantes_2019 = df_estudiantes_2019.drop(columnas_a_eliminar, axis=1)
df_estudiantes_2020 = df_estudiantes_2020.drop(columnas_a_eliminar, axis=1)

# UNIR LOS DF

In [19]:
# Verificamos que los DataFrames tengan el mismo número de columnas para una correcta concatenación.
print(df_estudiantes_2014.shape)
print(df_estudiantes_2015.shape)
print(df_estudiantes_2016.shape)
print(df_estudiantes_2017.shape)
print(df_estudiantes_2018.shape)
print(df_estudiantes_2019.shape)
print(df_estudiantes_2020.shape)

(38475, 33)
(40419, 33)
(42764, 33)
(45804, 33)
(44756, 33)
(50200, 33)
(52390, 33)


In [20]:
# Tomamos los nombres de las columnas de un DataFrame para eliminar algunos caracteres del nombre.
df_estudiantes_2018 = df_estudiantes_2018.rename(columns=lambda x: x.replace("\n", " "))
nuevos_nombres = df_estudiantes_2018.columns

In [21]:
# Renombramos las columnas exactamente igual en todos nuestros DataFrames.
df_estudiantes_2014.columns = nuevos_nombres
df_estudiantes_2015.columns = nuevos_nombres
df_estudiantes_2016.columns = nuevos_nombres
df_estudiantes_2017.columns = nuevos_nombres
df_estudiantes_2018.columns = nuevos_nombres
df_estudiantes_2019.columns = nuevos_nombres
df_estudiantes_2020.columns = nuevos_nombres

In [22]:
# concatenamos todos los df en uno solo
df_concatenado = pd.concat([df_estudiantes_2014, df_estudiantes_2015, df_estudiantes_2016, df_estudiantes_2017, df_estudiantes_2018, df_estudiantes_2019, df_estudiantes_2020], axis=0)
df = df_concatenado.reset_index(drop=True)

In [23]:
# verificamos el tamaño del df
print(df.shape)

(314808, 33)


In [24]:
# muestra informacion de las columnas 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314808 entries, 0 to 314807
Data columns (total 33 columns):
 #   Column                                   Non-Null Count   Dtype 
---  ------                                   --------------   ----- 
 0   Código de  la Institución                314808 non-null  object
 1   IES PADRE                                314808 non-null  object
 2   Institución de Educación Superior (IES)  314808 non-null  object
 3   Principal  o Seccional                   314808 non-null  object
 4   ID Sector IES                            314808 non-null  object
 5   Sector IES                               314808 non-null  object
 6   ID Caracter                              314808 non-null  object
 7   Caracter IES                             314808 non-null  object
 8   Código del  departamento (IES)           314808 non-null  object
 9   Departamento de  domicilio de la IES     314808 non-null  object
 10  Código del  Municipio (IES)              314

# FORMATO DE DATOS

In [25]:
# si la columna tiene numeros los pasa a int
lista = df.columns
for valor in lista:
    
    def convertir_a_numero(valor):
        try:
            return int(valor)
        except ValueError:
            return valor

    df[valor] = [convertir_a_numero(valor) for valor in df[valor]]

In [26]:
# pasa a minisculas todos las colunnas
for i in lista:
    df[i] = df[i].apply(lambda x: x.lower() if isinstance(x, str) else x)

In [27]:
# verificamos nuestros resultados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314808 entries, 0 to 314807
Data columns (total 33 columns):
 #   Column                                   Non-Null Count   Dtype 
---  ------                                   --------------   ----- 
 0   Código de  la Institución                314808 non-null  int64 
 1   IES PADRE                                314808 non-null  int64 
 2   Institución de Educación Superior (IES)  314808 non-null  object
 3   Principal  o Seccional                   314808 non-null  object
 4   ID Sector IES                            314808 non-null  int64 
 5   Sector IES                               314808 non-null  object
 6   ID Caracter                              314808 non-null  int64 
 7   Caracter IES                             314808 non-null  object
 8   Código del  departamento (IES)           314808 non-null  int64 
 9   Departamento de  domicilio de la IES     314808 non-null  object
 10  Código del  Municipio (IES)              314

In [28]:
df.head(2)

0  Código de  la Institución  IES PADRE  \
0                       1101       1101   
1                       1101       1101   

0 Institución de Educación Superior (IES) Principal  o Seccional  \
0        universidad nacional de colombia              principal   
1        universidad nacional de colombia              principal   

0  ID Sector IES Sector IES  ID Caracter Caracter IES  \
0              1    oficial            4  universidad   
1              1    oficial            4  universidad   

0  Código del  departamento (IES) Departamento de  domicilio de la IES  \
0                              11                          bogota d.c.   
1                              11                          bogota d.c.   

0  Código del  Municipio (IES) Municipio de domicilio de la IES  \
0                        11001                      bogota d.c.   
1                        11001                      bogota d.c.   

0 Código  SNIES del programa               Programa Académico  \
0                         38  especialidad en cirugia general   
1                         38  especialidad en cirugia general   

0 ID Nivel Académico Nivel Académico ID Nivel de Formación Nivel de Formación  \
0                  2        posgrado                     1    especializacion   
1                  2        posgrado                     1    especializacion   

0 ID Metodología Metodología ID Área  Área de Conocimiento Id_Nucleo  \
0              1  presencial       4  ciencias de la salud       445   
1              1  presencial       4  ciencias de la salud       445   

0 Núcleo Básico del Conocimiento (NBC) Código del  Departamento (Programa)  \
0                             medicina                                  11   
1                             medicina                                  11   

0 Departamento de oferta del programa Código del  Municipio (Programa)  \
0                         bogota d.c.                            11001   
1                         bogota d.c.                            11001   

0 Municipio de oferta del programa  ID Sexo       Sexo   Año  Semestre  \
0                      bogota d.c.        2   femenino  2014         1   
1                      bogota d.c.        1  masculino  2014         1   

0  Inscripciones 2018  
0                  48  
1                  81

# LIMPIEZA

In [29]:
# muestra los valores unicos por columna
def obtener_resumen_valores_unicos(df):
    # Obtener el número de valores únicos en cada columna
    valores_unicos = df.nunique()

    # Obtener el número total de valores en cada columna
    total_valores = df.count()

    # Combinar los resultados en un nuevo DataFrame
    resumen_valores_unicos = pd.DataFrame({
        'Columna': valores_unicos.index,
        'Valores Únicos': valores_unicos.values,
        'Total Valores': total_valores.values
    })
    
    return resumen_valores_unicos

# Imprimir el resumen de valores únicos
print(obtener_resumen_valores_unicos(df))

                                    Columna  Valores Únicos  Total Valores
0                 Código de  la Institución             338         314808
1                                 IES PADRE             289         314808
2   Institución de Educación Superior (IES)             366         314808
3                    Principal  o Seccional               2         314808
4                             ID Sector IES               2         314808
5                                Sector IES               2         314808
6                               ID Caracter               4         314808
7                              Caracter IES               7         314808
8            Código del  departamento (IES)              29         314808
9      Departamento de  domicilio de la IES              47         314808
10              Código del  Municipio (IES)              77         314808
11         Municipio de domicilio de la IES             116         314808
12               Código  

In [30]:
# muestra los valores nulos 
# Obtener la cantidad de valores 
valores_nulos = df.isnull().sum()

print(valores_nulos)

0
Código de  la Institución                     0
IES PADRE                                     0
Institución de Educación Superior (IES)       0
Principal  o Seccional                        0
ID Sector IES                                 0
Sector IES                                    0
ID Caracter                                   0
Caracter IES                                  0
Código del  departamento (IES)                0
Departamento de  domicilio de la IES          0
Código del  Municipio (IES)                   0
Municipio de domicilio de la IES              0
Código  SNIES del programa                    0
Programa Académico                            0
ID Nivel Académico                            0
Nivel Académico                               0
ID Nivel de Formación                         0
Nivel de Formación                            0
ID Metodología                                0
Metodología                                   0
ID Área                               

In [31]:
# Obtenenos los valores unicos y comparamos las colunas con ID vs los nombres
def obtener_diccionario(df, columna_a, columna_b, n = 2):
    '''
    Crea un diccionario que relaciona los códigos únicos de la columna_a con los nombres únicos de la columna_b.
    
    Parámetros:
        - df: DataFrame, el DataFrame de donde se obtendrán los datos.
        - columna_a: str, nombre de la columna que contiene los códigos.
        - columna_b: str, nombre de la columna que contiene los nombres.
        - n: int, valor mínimo de nombres únicos requeridos para incluirlos en el diccionario (por defecto, n=2).
        
    Retorna:
        Un diccionario donde las claves son los códigos únicos y los valores son listas de nombres únicos 
        asociados a cada código, siempre y cuando haya al menos n nombres únicos para ese código.
    '''   
    codigos_unicos = df[columna_a].unique()
    diccionario = {}

    # Iterar sobre los códigos únicos
    for codigo in codigos_unicos:
        # Obtener los valores únicos de los nombres para cada código
        nombres_unicos = df[df[columna_a] == codigo][columna_b].unique()

        # Verificar si hay más de 2 valores únicos de nombres
        if len(nombres_unicos) >= n:
            # Asignar los nombres únicos como valor para cada código en el diccionario
            diccionario[codigo] = nombres_unicos.tolist()

    return diccionario


In [32]:

resultado = obtener_diccionario(df, 'IES PADRE', 'Institución de Educación Superior (IES)',1)
resultado1 = obtener_diccionario(df, 'IES PADRE', 'Institución de Educación Superior (IES)')
resultado2 = obtener_diccionario(df, 'Institución de Educación Superior (IES)', 'IES PADRE')

# Imprimir la cantidad de códigos únicos con al menos 2 nombres distintos asociados.
print(len(resultado1))
# Imprimir el resultado2, que muestra los nombres únicos de cada código.
print(resultado2)

# Iterar sobre los valores del resultado2 (que son las listas de nombres únicos para cada código).
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

69
{'instituto nacional de formacion tecnica profesional de s': [4102, 4106]}
El codigo/ID 4102 tiene 2 categorias distintas ['instituto nacional de formacion tecnica profesional de san juan del cesar', 'instituto nacional de formacion tecnica profesional de s']
El codigo/ID 4106 tiene 2 categorias distintas ['instituto nacional de formacion tecnica profesional de san andres', 'instituto nacional de formacion tecnica profesional de s']


Instituto Nacional De Formacion Tecnica Profesional De S' es el único que tiene dos códigos. Manualmente, lo pondremos como 'Instituto Nacional De Formacion Tecnica Profesional De San Juan Del Cesar' cuando el código sea 4102, y como 'Instituto Nacional De Formacion Tecnica Profesional De San Andres' cuando el código sea 4106
* 4102: ['Instituto Nacional De Formacion Tecnica Profesional De San Juan Del Cesar', 'Instituto Nacional De Formacion Tecnica Profesional De S'],
* 4106: ['Instituto Nacional De Formacion Tecnica Profesional De San Andres', 'Instituto Nacional De Formacion Tecnica Profesional De S'],

In [33]:
# Filtrar y asignar el valor 
df.loc[df['IES PADRE'] == 4102, 'Institución de Educación Superior (IES)'] = 'instituto nacional de formacion tecnica profesional de san juan del cesar'
df.loc[df['IES PADRE'] == 4106, 'Institución de Educación Superior (IES)'] = 'instituto nacional de formacion tecnica profesional de san andres'

In [34]:
# Esta funcion entrega un diccionario con los valores a ser reemplazado 
def obtener_diccionario_remplaza(d_f, col_codigos, col_valores):
    # Obtenemos los códigos únicos en la columna 'col_codigos'
    codigos_unicos = d_f[col_codigos].unique()
    diccionario = {}
    
     # Creamos un diccionario donde las claves son los códigos únicos y los valores son listas de nombres únicos
    for codigo in codigos_unicos:
        nombres_unicos = d_f[df[col_codigos] == codigo][col_valores].unique()
        
        if len(nombres_unicos) > 1:
            diccionario[codigo] = nombres_unicos.tolist()
            
    # Creamos una lista con los primeros valores de cada lista de nombres y construimos un nuevo diccionario
    lista_valores = [valor[0] for valor in diccionario.values()]
    diccionario_actualizado = {lista_valores[i]: valor for i, valor in enumerate(diccionario.values())}
    
    # Construimos el diccionario invertido
    diccionario_invertido = {}

    for clave, valores in diccionario_actualizado.items():
        for valor in valores:
            diccionario_invertido.setdefault(valor, []).append(clave)
    
    return diccionario_invertido

In [35]:
# Obtenemos los valores y remplazamos
p2 = obtener_diccionario_remplaza(df, 'Código de  la Institución', 'Institución de Educación Superior (IES)')
print(p2)

{'universidad de nariño': ['universidad de nariño'], 'universidad de nari¿o': ['universidad de nariño'], 'universidad catolica de oriente': ['universidad catolica de oriente'], 'universidad catolica de oriente -uco': ['universidad catolica de oriente'], 'universidad autonoma del caribe': ['universidad autonoma del caribe'], 'universidad autonoma del caribe- uniautonoma': ['universidad autonoma del caribe'], 'universidad antonio nariño': ['universidad antonio nariño'], 'universidad antonio nari¿o': ['universidad antonio nariño'], 'universidad de ciencias aplicadas y ambientales udca.': ['universidad de ciencias aplicadas y ambientales udca.'], 'universidad de ciencias aplicadas y ambientales - udca': ['universidad de ciencias aplicadas y ambientales udca.'], 'institucion universitaria bellas artes y ciencias de bolivar': ['institucion universitaria bellas artes y ciencias de bolivar'], 'institucion universitaria bellas artes y ciencias de bol': ['institucion universitaria bellas artes y

In [36]:
# Reemplazamos los valores
p2 = {k: v[0] for k, v in p2.items()}
df["Institución de Educación Superior (IES)"] = df["Institución de Educación Superior (IES)"].replace(p2)

De igual forma comparamos las demas colunmas con sus ID

## Caracter IES

In [37]:
resultado = obtener_diccionario(df, 'ID Caracter', 'Caracter IES',1)
resultado1 = obtener_diccionario(df, 'ID Caracter', 'Caracter IES')
resultado2 = obtener_diccionario(df, 'Caracter IES', 'ID Caracter')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

3
{}


In [38]:
# Obtenemos los valores y reemplazamos
p2 = obtener_diccionario_remplaza(df, 'ID Caracter', 'Caracter IES')
p2 = {k: v[0] for k, v in p2.items()}
df["Caracter IES"] = df["Caracter IES"].replace(p2)

## Departamento de  domicilio de la IES

In [39]:
resultado = obtener_diccionario(df, 'Código del  departamento (IES)', 'Departamento de  domicilio de la IES',1)
resultado1 = obtener_diccionario(df, 'Código del  departamento (IES)', 'Departamento de  domicilio de la IES')
resultado2 = obtener_diccionario(df, 'Departamento de  domicilio de la IES', 'Código del  departamento (IES)')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

14
{}


In [40]:
# Obtenemos los valores y reemplazamos
p2 = obtener_diccionario_remplaza(df, 'Código del  departamento (IES)', 'Departamento de  domicilio de la IES')
p2 = {k: v[0] for k, v in p2.items()}
df["Departamento de  domicilio de la IES"] = df["Departamento de  domicilio de la IES"].replace(p2)

## Municipio de domicilio de la IES

In [41]:
resultado = obtener_diccionario(df, 'Código del  Municipio (IES)', 'Municipio de domicilio de la IES',1)
resultado1 = obtener_diccionario(df, 'Código del  Municipio (IES)', 'Municipio de domicilio de la IES')
resultado2 = obtener_diccionario(df, 'Municipio de domicilio de la IES', 'Código del  Municipio (IES)')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))


29
{'santa rosa d': [5686, 66682]}
El codigo/ID 5686 tiene 2 categorias distintas ['santa rosa de osos', 'santa rosa d']
El codigo/ID 66682 tiene 2 categorias distintas ['santa rosa de cabal', 'santa rosa d']


In [42]:
# Filtrar y asignar el valor 
df.loc[df['Código del  Municipio (IES)'] == 5686, 'Municipio de domicilio de la IES'] = 'santa rosa de osos'
df.loc[df['Código del  Municipio (IES)'] == 66682, 'Municipio de domicilio de la IES'] = 'santa rosa de cabal'

In [43]:
# Obtenemos los valores y reemplazamos
p2 = obtener_diccionario_remplaza(df, 'Código del  Municipio (IES)', 'Municipio de domicilio de la IES')
p2 = {k: v[0] for k, v in p2.items()}
df["Municipio de domicilio de la IES"] = df["Municipio de domicilio de la IES"].replace(p2)

## Programa Académico

In [44]:
'''
resultado1 = obtener_diccionario(df, 'Código  SNIES del programa', 'Programa Académico',1)
resultado2 = obtener_diccionario(df, 'Programa Académico', 'Código  SNIES del programa')

for i in resultado2.values():
    for n in i:
        if len(resultado1[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado1[n]))
            
'''


"\nresultado1 = obtener_diccionario(df, 'Código  SNIES del programa', 'Programa Académico',1)\nresultado2 = obtener_diccionario(df, 'Programa Académico', 'Código  SNIES del programa')\n\nfor i in resultado2.values():\n    for n in i:\n        if len(resultado1[n]) >= 2:\n            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado1[n]))\n            \n"

## Nivel Académico

In [45]:
resultado = obtener_diccionario(df, 'ID Nivel Académico', 'Nivel Académico',1)
resultado1 = obtener_diccionario(df, 'ID Nivel Académico', 'Nivel Académico')
resultado2 = obtener_diccionario(df, 'Nivel Académico', 'ID Nivel Académico')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

0
{'no aplica': ['no aplica', 0]}


In [46]:
# Filtrar y asignar el valor
 
df.loc[df['Nivel Académico'] == 'no aplica', 'ID Nivel Académico'] = 0

## Nivel de Formación

In [47]:
resultado = obtener_diccionario(df, 'ID Nivel de Formación', 'Nivel de Formación',1)
resultado1 = obtener_diccionario(df, 'ID Nivel de Formación', 'Nivel de Formación')
resultado2 = obtener_diccionario(df, 'Nivel de Formación', 'ID Nivel de Formación')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

6
{'no aplica': ['no aplica', 0]}


In [48]:
# Filtrar y asignar el valor 
df.loc[df['Nivel de Formación'] == 'no aplica', 'ID Nivel de Formación'] = 0

In [49]:
# Obtenemos los valores a remplazar
p2 = obtener_diccionario_remplaza(df, 'ID Nivel de Formación', 'Nivel de Formación')
p2 = {k: v[0] for k, v in p2.items()}
df["Nivel de Formación"] = df["Nivel de Formación"].replace(p2)

## Metodología

In [50]:
resultado = obtener_diccionario(df, 'ID Metodología', 'Metodología',1)
resultado1 = obtener_diccionario(df, 'ID Metodología', 'Metodología')
resultado2 = obtener_diccionario(df, 'Metodología', 'ID Metodología')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

2
{'no aplica': ['no aplica', 0]}


In [51]:
# Filtrar y asignar el valor 
df.loc[df['Metodología'] == 'no aplica', 'ID Metodología'] = 0

In [52]:
# Obtenemos los valores a remplazar
p2 = obtener_diccionario_remplaza(df, 'ID Metodología', 'Metodología')
p2 = {k: v[0] for k, v in p2.items()}
df["Metodología"] = df["Metodología"].replace(p2)

## Área de Conocimiento  

In [53]:
resultado = obtener_diccionario(df, 'ID Área', 'Área de Conocimiento',1)
resultado1 = obtener_diccionario(df, 'ID Área', 'Área de Conocimiento')
resultado2 = obtener_diccionario(df, 'Área de Conocimiento', 'ID Área')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

5
{'no aplica': ['no aplica', 0]}


In [54]:
# Filtrar y asignar el valor 
df.loc[df['Área de Conocimiento'] == 'no aplica', 'ID Área'] = 0

In [55]:
# Obtenemos los valores a remplazar
p2 = obtener_diccionario_remplaza(df, 'ID Área', 'Área de Conocimiento')
p2 = {k: v[0] for k, v in p2.items()}
df["Área de Conocimiento"] = df["Área de Conocimiento"].replace(p2)

## Núcleo Básico del Conocimiento (NBC)

In [56]:
resultado = obtener_diccionario(df, 'Id_Nucleo', 'Núcleo Básico del Conocimiento (NBC)',1)
resultado1 = obtener_diccionario(df, 'Id_Nucleo', 'Núcleo Básico del Conocimiento (NBC)')
resultado2 = obtener_diccionario(df, 'Núcleo Básico del Conocimiento (NBC)', 'Id_Nucleo')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

53
{'sin clasificar': [-4, -3, -5, -6, -9, -8, -2, 'sin clasificar'], 'no aplica': ['no aplica', 0]}
El codigo/ID -4 tiene 2 categorias distintas ['sin clasificar', nan]
El codigo/ID -3 tiene 2 categorias distintas ['sin clasificar', nan]
El codigo/ID -5 tiene 2 categorias distintas ['sin clasificar', nan]
El codigo/ID -6 tiene 2 categorias distintas ['sin clasificar', nan]
El codigo/ID -9 tiene 2 categorias distintas ['sin clasificar', nan]
El codigo/ID -8 tiene 2 categorias distintas ['sin clasificar', nan]
El codigo/ID -2 tiene 2 categorias distintas ['sin clasificar', nan]


In [57]:
# Filtrar y asignar el valor 
df.loc[df['Núcleo Básico del Conocimiento (NBC)'] == 'no aplica', 'Id_Nucleo'] = 0
df.loc[df['Id_Nucleo'] == -4 , 'Id_Nucleo'] = -1
df.loc[df['Id_Nucleo'] == -3 , 'Id_Nucleo'] = -1
df.loc[df['Id_Nucleo'] == -5 , 'Id_Nucleo'] = -1
df.loc[df['Id_Nucleo'] == -6 , 'Id_Nucleo'] = -1
df.loc[df['Id_Nucleo'] == -9 , 'Id_Nucleo'] = -1
df.loc[df['Id_Nucleo'] == -8 , 'Id_Nucleo'] = -1
df.loc[df['Id_Nucleo'] == -2 , 'Id_Nucleo'] = -1
df.loc[df['Núcleo Básico del Conocimiento (NBC)'] == 'sin clasificar', 'Id_Nucleo'] = -1

In [58]:
# Obtenemos los valores a remplazar
p2 = obtener_diccionario_remplaza(df, 'Id_Nucleo', 'Núcleo Básico del Conocimiento (NBC)')
p2 = {k: v[0] for k, v in p2.items()}
df["Núcleo Básico del Conocimiento (NBC)"] = df["Núcleo Básico del Conocimiento (NBC)"].replace(p2)

## Departamento de oferta del programa

In [59]:
resultado = obtener_diccionario(df, 'Código del  Departamento (Programa)', 'Departamento de oferta del programa',1)
resultado1 = obtener_diccionario(df, 'Código del  Departamento (Programa)', 'Departamento de oferta del programa')
resultado2 = obtener_diccionario(df, 'Departamento de oferta del programa', 'Código del  Departamento (Programa)')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

14
{'meta': [50, 52], 'cesar': [20, 22], 'sucre': [70, 72], 'no aplica': ['no aplica', 0]}
El codigo/ID 52 tiene 2 categorias distintas ['narino', 'nariño', 'narinio', 'meta']


In [60]:
# Filtrar y asignar el valor 
df.loc[df['Departamento de oferta del programa'] == 'no aplica', 'Código del  Departamento (Programa)'] = 0
df.loc[df['Departamento de oferta del programa'] == 'cesar', 'Código del  Departamento (Programa)'] = 20
df.loc[df['Departamento de oferta del programa'] == 'sucre', 'Código del  Departamento (Programa)'] = 70
df.loc[df['Código del  Departamento (Programa)'] == 52, 'Departamento de oferta del programa'] = 'nariño'

In [61]:
# Obtenemos los valores a remplazar
p2 = obtener_diccionario_remplaza(df, 'Código del  Departamento (Programa)', 'Departamento de oferta del programa')
p2 = {k: v[0] for k, v in p2.items()}
df["Departamento de oferta del programa"] = df["Departamento de oferta del programa"].replace(p2)

## Municipio de oferta del programa

In [62]:
resultado = obtener_diccionario(df, 'Código del  Municipio (Programa)', 'Municipio de oferta del programa',1)
resultado1 = obtener_diccionario(df, 'Código del  Municipio (Programa)', 'Municipio de oferta del programa')
resultado2 = obtener_diccionario(df, 'Municipio de oferta del programa', 'Código del  Municipio (Programa)')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

162
{'rionegro': [5615, 68615], 'barbosa': [68077, 5079], 'armenia': [63001, 5059], 'san andres': [88001, 5647], 'florencia': [18001, 19290], 'villanueva': [44874, 85440, 13873, 68872], 'san francisco': [86755, 25658], 'la union': [70400, 52399, 76400], 'sabanalarga': [8638, 85300, 5628], 'caldas': [5129, 15131], 'concordia': [5209, 47205], 'granada': [50313, 25312, 5313], 'chima': [23168, 68176], 'puerto rico': [18592, 50590], 'el tambo': [52260, 19256], 'ricaurte': [25612, 52612], 'guadalupe': [41319, 5315], 'albania': [18029, 44035], 'san pablo': [52693, 13670], 'buenavista': [23079, 63111, 70110], 'mosquera': [25473, 52473], 'miraflores': [15455, 95200], 'riosucio': [17614, 27615], 'san martin': [50689, 20770], 'san pedro': [70717, 76670, 5664], 'san carlos': [5649, 23678], 'no aplica': ['no aplica', 0], 'la unión': [70400, 76400, 52399], 'san martín': [50689, 20770], 'santa maria': [15690, 41676], 'cordoba': [13212, 52215], 'la vega': [25402, 19397], 'morales': [13473, 19473], 'có

In [63]:
# Filtrar y asignar el valor 
df.loc[df['Código del  Municipio (Programa)'] == 88001, 'Municipio de oferta del programa'] = 'san andrés'
df.loc[df['Código del  Municipio (Programa)'] == 5647, 'Municipio de oferta del programa'] = 'san andrés de cuerquía'
df.loc[df['Municipio de oferta del programa'] == 'la union', 'Código del  Municipio (Programa)'] = 70400
df.loc[df['Municipio de oferta del programa'] == 'la unión', 'Código del  Municipio (Programa)'] = 70400
df.loc[df['Municipio de oferta del programa'] == 'san martin', 'Código del  Municipio (Programa)'] = 50689
df.loc[df['Municipio de oferta del programa'] == 'san martín', 'Código del  Municipio (Programa)'] = 50689
df.loc[df['Municipio de oferta del programa'] == 'cordoba', 'Código del  Municipio (Programa)'] = 13212
df.loc[df['Municipio de oferta del programa'] == 'córdoba', 'Código del  Municipio (Programa)'] = 13212
df.loc[df['Código del  Municipio (Programa)'] == 15690, 'Municipio de oferta del programa'] = 'santa maría'
df.loc[df['Código del  Municipio (Programa)'] == 5664, 'Municipio de oferta del programa'] = 'san pedro de los milagros'
df.loc[df['Código del  Municipio (Programa)'] == 44035, 'Municipio de oferta del programa'] = 'albania (guajira)'

In [64]:
# Obtenemos los valores a remplazar
p2 = obtener_diccionario_remplaza(df, 'Código del  Municipio (Programa)', 'Municipio de oferta del programa')
p2 = {k: v[0] for k, v in p2.items()}
df["Municipio de oferta del programa"] = df["Municipio de oferta del programa"].replace(p2)

## Sexo 

In [65]:
resultado = obtener_diccionario(df, 'ID Sexo', 'Sexo',1)
resultado1 = obtener_diccionario(df, 'ID Sexo', 'Sexo')
resultado2 = obtener_diccionario(df, 'Sexo', 'ID Sexo')
print(len(resultado1))
print(resultado2)
for i in resultado2.values():
    for n in i:
        if len(resultado[n]) >= 2:
            print('El codigo/ID {} tiene 2 categorias distintas {}'.format (n,resultado[n]))

2
{}


In [66]:
# Obtenemos los valores a remplazar
p2 = obtener_diccionario_remplaza(df, 'ID Sexo', 'Sexo')
p2 = {k: v[0] for k, v in p2.items()}
df["Sexo"] = df["Sexo"].replace(p2)

# EXPLORACION

In [67]:
df.describe(include='all')

0       Código de  la Institución      IES PADRE  \
count               314808.000000  314808.000000   
unique                        NaN            NaN   
top                           NaN            NaN   
freq                          NaN            NaN   
mean                  3001.120013    2992.056835   
std                   2439.196934    2430.590999   
min                   1101.000000    1101.000000   
25%                   1710.000000    1710.000000   
50%                   2102.000000    2102.000000   
75%                   2833.000000    2833.000000   
max                   9933.000000    9931.000000   

0               Institución de Educación Superior (IES)  \
count                                            314808   
unique                                              289   
top     universidad nacional abierta y a distancia unad   
freq                                              43682   
mean                                                NaN   
std                                                 NaN   
min                                                 NaN   
25%                                                 NaN   
50%                                                 NaN   
75%                                                 NaN   
max                                                 NaN   

0      Principal  o Seccional  ID Sector IES Sector IES    ID Caracter  \
count                  314808  314808.000000     314808  314808.000000   
unique                      2            NaN          2            NaN   
top                 principal            NaN    privada            NaN   
freq                   293947            NaN     165091            NaN   
mean                      NaN       1.524418        NaN       3.452533   
std                       NaN       0.499404        NaN       0.827747   
min                       NaN       1.000000        NaN       1.000000   
25%                       NaN       1.000000        NaN       3.000000   
50%                       NaN       2.000000        NaN       4.000000   
75%                       NaN       2.000000        NaN       4.000000   
max                       NaN       2.000000        NaN       4.000000   

0      Caracter IES  Código del  departamento (IES)  \
count        314808                   314808.000000   
unique            4                             NaN   
top     universidad                             NaN   
freq         201879                             NaN   
mean            NaN                       20.881858   
std             NaN                       21.966241   
min             NaN                        5.000000   
25%             NaN                       11.000000   
50%             NaN                       11.000000   
75%             NaN                       17.000000   
max             NaN                       91.000000   

0      Departamento de  domicilio de la IES  Código del  Municipio (IES)  \
count                                314808                314808.000000   
unique                                   29                          NaN   
top                             bogota d.c.                          NaN   
freq                                 166336                          NaN   
mean                                    NaN                 20910.148087   
std                                     NaN                 21991.065412   
min                                     NaN                  5001.000000   
25%                                     NaN                 11001.000000   
50%                                     NaN                 11001.000000   
75%                                     NaN                 17001.000000   
max                                     NaN                 91001.000000   

0      Municipio de domicilio de la IES  Código  SNIES del programa  \
count                            314808                    314808.0   
unique                               77                     1

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314808 entries, 0 to 314807
Data columns (total 33 columns):
 #   Column                                   Non-Null Count   Dtype 
---  ------                                   --------------   ----- 
 0   Código de  la Institución                314808 non-null  int64 
 1   IES PADRE                                314808 non-null  int64 
 2   Institución de Educación Superior (IES)  314808 non-null  object
 3   Principal  o Seccional                   314808 non-null  object
 4   ID Sector IES                            314808 non-null  int64 
 5   Sector IES                               314808 non-null  object
 6   ID Caracter                              314808 non-null  int64 
 7   Caracter IES                             314808 non-null  object
 8   Código del  departamento (IES)           314808 non-null  int64 
 9   Departamento de  domicilio de la IES     314808 non-null  object
 10  Código del  Municipio (IES)              314

In [69]:
print(obtener_resumen_valores_unicos(df))

                                    Columna  Valores Únicos  Total Valores
0                 Código de  la Institución             338         314808
1                                 IES PADRE             289         314808
2   Institución de Educación Superior (IES)             289         314808
3                    Principal  o Seccional               2         314808
4                             ID Sector IES               2         314808
5                                Sector IES               2         314808
6                               ID Caracter               4         314808
7                              Caracter IES               4         314808
8            Código del  departamento (IES)              29         314808
9      Departamento de  domicilio de la IES              29         314808
10              Código del  Municipio (IES)              77         314808
11         Municipio de domicilio de la IES              77         314808
12               Código  

In [70]:
# Obtener la cantidad de valores 
valores_nulos = df.isnull().sum()

print(valores_nulos)

0
Código de  la Institución                    0
IES PADRE                                    0
Institución de Educación Superior (IES)      0
Principal  o Seccional                       0
ID Sector IES                                0
Sector IES                                   0
ID Caracter                                  0
Caracter IES                                 0
Código del  departamento (IES)               0
Departamento de  domicilio de la IES         0
Código del  Municipio (IES)                  0
Municipio de domicilio de la IES             0
Código  SNIES del programa                   0
Programa Académico                           0
ID Nivel Académico                           0
Nivel Académico                              0
ID Nivel de Formación                        0
Nivel de Formación                           0
ID Metodología                               0
Metodología                                  0
ID Área                                      0
Área de Con

In [71]:
df.to_csv('Estudiantes_inscritos.csv', index=False, encoding='utf-8')

In [72]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.
